Squashed commit of XError and Debugging Branch
commit 15db00a1e35522731e7a68b8c3f666b4db5d1fb8
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 06:34:11 2020 -0700

    Explicitly state how to compile 'borked'

    Apparently, gcc for 32-bit Linux requires libraries (-lX11 -lXmu)
    to come AFTER the object and source files. Using the implicit
    rule works fine on 64-bit Linux, but with the same version of gcc (8.3)
    and autoconf (2.69), it barfs with "Undefined reference to XFree", etc.

commit ab81ab7f5f9fd4d92d8047c30e66355553bf0334
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 05:40:49 2020 -0700

    Finish immediately after sending TARGETS

    Otherwise, requestor does not get deleted and the xclip process hangs
    around too long.

commit 74f4ac097062d757044aee2f37a54179701f4911
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 05:27:28 2020 -0700

    Print "Event received from" *after* running xcfetchname

    as it might cause an error and print other debugging info in
    the middle.

commit 83e4f33c6585a66b9597f842e2b666d654c5d6f9
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 05:17:57 2020 -0700

    Indent XErrors and only print target if non-null

commit 0f46ebaa43dd49581023895c76b47353afc7e6e5
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 05:07:51 2020 -0700

    Properly free string from XGetAtomName

commit 1aaf529713ca71b1db55c5d9884d2ddc9652c15d
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 05:04:27 2020 -0700

    Show requested target (e.g., "image/jpeg")

commit 16c4325004132aaf631ab7236cfc4b4f8c2070e6
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 04:42:35 2020 -0700

    note: this triggers X's BadWindow error and runs xchandler().

commit d6dc6fff4f756425653a38ab7e35e67c35c76d88
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 04:40:33 2020 -0700

    Add 0x prefix to hex output

commit 532c959e172eab997f8b737212fd4cef58e4e902
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 04:25:32 2020 -0700

    Print requestor (window IDs) as hex

commit 974c89d80f387c345ac7c13fed20302b30be2a07
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 04:24:33 2020 -0700

    Ignore borked binary

commit 0685839d9d40833f5db06f17507a71debdc2d710
Author: b9 <hackerb9@member.fsf.org>
Date:   Wed Sep 30 03:57:16 2020 -0700

    Reindent to 4 spaces, same as .c files

commit 576348431cb591591832c6731cc695677f8d34a9
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 22:56:37 2020 -0700

    Print PASS or FAIL on same line as test name

commit 449f3487259cab6f95659882ba7500e95e5196d1
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 22:51:45 2020 -0700

    trap cleanup to killall and rm tmpfiles

commit 59ae4d5ff480944f77effae34a8a76b00d9acad9
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 22:43:23 2020 -0700

    Speedup testing by doubling test datafile size

    basically: cat a a > b  &&  mv b a

commit 93b164205e5ad9ba6bba78e465bc407bc7eaa9e7
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 22:21:27 2020 -0700

    Exit script immediately if any test fails

    So that it won't scroll off the screen.

commit 3ce4c303817698f3b00afc457a1f411f436f836d
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 22:20:57 2020 -0700

    Check INCR mode using a binary file

commit b5ae50d8fc3971973bb650e8be062b5009876b10
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 22:07:21 2020 -0700

    Temp files don't need to change name every loop

commit 86dfa5b9d09deca984d3be6f47795d316eae0764
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 22:03:40 2020 -0700

    Check execute bit

commit 3f9aceb013315aa4137b239c155ea2f797327806
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 22:03:01 2020 -0700

    Use fractional sleep, if available

commit 338dbde8c52fcb2acaf477c38ac46ea346e1365a
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 18:12:55 2020 -0700

    move xchandler to xclib where it belongs

commit 54edd53596f3b6d73271d2a6fafc80562e816e5d
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 17:58:16 2020 -0700

    Match verbose indentation by request

commit 9fd0955ea16f58aacde10a6eab83affe25940742
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 17:31:22 2020 -0700

    Add a lot more requestor debugging, plus possible fix

commit 432dbda9f3ca1c3dcb61960ce887a2537f6d0d5c
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 01:59:30 2020 -0700

    initial cut of cleanUpRequestors when BadWindow error

commit d3b44173823b76843ae35e97f9cbb7fbd9582b11
Author: b9 <hackerb9@member.fsf.org>
Date:   Tue Sep 29 01:49:52 2020 -0700

    More verbose debugging when catching XError and DEBUG is on

commit bab9ec769a0730bfdd3bf817ed74cc0c259359fb
Author: b9 <hackerb9@member.fsf.org>
Date:   Sun Sep 27 23:40:14 2020 -0700

    Use XSetErrorHandler so xclip won't die on BadWindow

    In case the the other window disappears.