Explicitly state how to compile 'borked'
Apparently, gcc for 32-bit Linux requires libraries (-lX11 -lXmu)
to come AFTER the object and source files. Using the implicit
rule works fine on 64-bit Linux, but with the same version of gcc (8.3)
and autoconf (2.69), it barfs with "Undefined reference to XFree", etc.